version: 2
jobs:
  build:
    working_directory: /go/src/github.com/gjbae1212/go-module

    docker:
    - image: golang:1.12

    environment:
      GOPATH: /go

    steps:
    - checkout

    - run:
        name: RUN UNIT TEST
        environment:
          GO111MODULE: "on"
        command: bash local.sh test

    - run:
        name: CODECOV
        command: bash local.sh codecov
